runtime: python37

instance_class: F1

# GCP requires that we must have a service named 'default' so we use this
# as our test env
service: default

env_variables:
  PROJECT_ID: "homie-mt-2021"
  DJANGO_SETTINGS_MODULE: "homie.settings.test"

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
  - url: /static
    static_dir: static/

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto