# Generated by Django 3.2 on 2021-05-18 09:35

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('create_time', common.models.IntDateTimeField()),
                ('update_time', common.models.IntDateTimeField()),
            ],
            options={
                'db_table': 'wallet_tab',
            },
        ),
    ]
