# Generated by Django 3.2 on 2021-05-27 03:43

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', common.models.IntDateTimeField()),
                ('update_time', common.models.IntDateTimeField()),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'income_group_tab',
            },
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', common.models.IntDateTimeField()),
                ('update_time', common.models.IntDateTimeField()),
                ('name', models.CharField(max_length=50, unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.incomegroup')),
            ],
            options={
                'verbose_name_plural': 'income categories',
                'db_table': 'income_category_tab',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', common.models.IntDateTimeField()),
                ('update_time', common.models.IntDateTimeField()),
                ('name', models.CharField(blank=True, max_length=500)),
                ('value', models.PositiveIntegerField()),
                ('receive_time', common.models.IntDateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.incomecategory')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.wallet')),
            ],
            options={
                'db_table': 'income_tab',
            },
        ),
    ]
