# Generated by Django 3.2 on 2021-05-27 10:09

import common.models
from django.db import migrations, models
import django.db.models.deletion
import portfolio.time_util


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_income_incomecategory_incomegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', common.models.IntDateTimeField()),
                ('update_time', common.models.IntDateTimeField()),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'expense_group_tab',
            },
        ),
        migrations.AlterField(
            model_name='income',
            name='receive_time',
            field=common.models.IntDateTimeField(default=portfolio.time_util.now),
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', common.models.IntDateTimeField()),
                ('update_time', common.models.IntDateTimeField()),
                ('name', models.CharField(max_length=50, unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.expensegroup')),
            ],
            options={
                'verbose_name_plural': 'expense categories',
                'db_table': 'expense_category_tab',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', common.models.IntDateTimeField()),
                ('update_time', common.models.IntDateTimeField()),
                ('name', models.CharField(blank=True, max_length=500)),
                ('value', models.PositiveIntegerField()),
                ('receive_time', common.models.IntDateTimeField(default=portfolio.time_util.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.expensecategory')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.wallet')),
            ],
            options={
                'db_table': 'expense_tab',
            },
        ),
    ]
