# Generated by Django 3.2 on 2021-05-27 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_auto_20210527_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='receive_time',
        ),
        migrations.RemoveField(
            model_name='income',
            name='receive_time',
        ),
        migrations.AddField(
            model_name='expense',
            name='pay_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='income',
            name='receive_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
