# Generated by Django 3.2 on 2021-06-02 14:20

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_auto_20210527_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', common.models.IntDateTimeField()),
                ('update_time', common.models.IntDateTimeField()),
                ('limit', models.PositiveIntegerField()),
                ('expense_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.expensegroup')),
            ],
            options={
                'db_table': 'budget_tab',
            },
        ),
    ]
