# Generated by Django 3.2 on 2021-06-02 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='expense_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='money.expensegroup'),
        ),
    ]
