# Generated by Django 3.2 on 2021-05-02 02:42

from django.db import migrations, models
import django.db.models.deletion
import portfolio.models
import portfolio.time_util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('latest_price', models.PositiveIntegerField(blank=True, help_text='latest known price of this symbol in vnd', null=True)),
                ('create_time', portfolio.models.IntDateTimeField()),
                ('update_time', portfolio.models.IntDateTimeField()),
            ],
            options={
                'db_table': 'holding_tab',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Buy'), (2, 'Sell'), (3, 'Deposit')], default=1)),
                ('price', models.PositiveIntegerField(help_text='in vnd')),
                ('amount', models.PositiveIntegerField()),
                ('fee', models.PositiveIntegerField(default=0, help_text='in vnd')),
                ('transaction_time', portfolio.models.IntDateTimeField(default=portfolio.time_util.now)),
                ('create_time', portfolio.models.IntDateTimeField()),
                ('update_time', portfolio.models.IntDateTimeField()),
                ('holding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolio.holding')),
            ],
            options={
                'db_table': 'transaction_tab',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['symbol'], name='idx_symbol'),
        ),
    ]
