# Generated by Django 3.1.7 on 2021-04-01 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee',
            field=models.PositiveIntegerField(default=0, help_text='in vnd'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='in vnd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='symbol',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Buy'), (2, 'Sell'), (3, 'Deposit')], default=1),
        ),
        migrations.AddField(
            model_name='transaction',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
