# Generated by Django 3.1.7 on 2021-04-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210401_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
