# Generated by Django 3.1.7 on 2021-04-01 05:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
