# Generated by Django 3.2 on 2021-04-24 11:06

from django.db import migrations
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_transaction_transaction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=portfolio.models.IntDateTimeField(default=0),
            preserve_default=False,
        ),
    ]
