# Generated by Django 3.2 on 2021-04-25 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_transaction_created_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='transaction_tab',
        ),
    ]
