# Generated by Django 3.2 on 2021-04-25 15:43

from django.db import migrations
import portfolio.models
import portfolio.time_util


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_transaction_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='create_time',
            field=portfolio.models.IntDateTimeField(default=portfolio.time_util.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='update_time',
            field=portfolio.models.IntDateTimeField(blank=True),
        ),
    ]
