# Generated by Django 3.2 on 2021-05-01 15:44

from django.db import migrations, models
import django.db.models.deletion
import portfolio.models
import portfolio.time_util


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_transaction_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('latest_price', models.PositiveIntegerField(blank=True, help_text='latest known price of this symbol in vnd', null=True)),
                ('create_time', portfolio.models.IntDateTimeField()),
                ('update_time', portfolio.models.IntDateTimeField()),
            ],
            options={
                'db_table': 'holding_tab',
            },
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='create_time',
            field=portfolio.models.IntDateTimeField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_time',
            field=portfolio.models.IntDateTimeField(default=portfolio.time_util.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='update_time',
            field=portfolio.models.IntDateTimeField(),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['symbol'], name='idx_symbol'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='holding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolio.holding'),
        ),
    ]
