# Generated by Django 3.2 on 2021-04-25 15:53

from django.db import migrations
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20210425_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='update_time',
            field=portfolio.models.IntDateTimeField(blank=True, null=True),
        ),
    ]
