# Generated by Django 3.2 on 2021-04-25 16:01

from django.db import migrations
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_transaction_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='create_time',
            field=portfolio.models.IntDateTimeField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='update_time',
            field=portfolio.models.IntDateTimeField(default=0),
            preserve_default=False,
        ),
    ]
