# Generated by Django 3.2 on 2021-04-27 07:48

from django.db import migrations
import portfolio.models
import portfolio.time_util


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20210425_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_time',
            field=portfolio.models.IntDateTimeField(default=portfolio.time_util.now),
        ),
    ]
