# Generated by Django 3.2 on 2021-05-01 04:46

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_transaction_transaction_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('latest_price', models.PositiveIntegerField(help_text='latest known price of this symbol in vnd')),
                ('create_time', portfolio.models.IntDateTimeField()),
                ('update_time', portfolio.models.IntDateTimeField()),
            ],
            options={
                'db_table': 'holding_tab',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['symbol'], name='idx_symbol'),
        ),
    ]
