# Generated by Django 3.2 on 2021-05-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20210501_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='latest_price',
            field=models.PositiveIntegerField(blank=True, help_text='latest known price of this symbol in vnd', null=True),
        ),
    ]
