# Generated by Django 3.2 on 2021-05-01 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_holding_latest_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='holding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolio.holding'),
        ),
    ]
